name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: installing Sass and Rollup
        run: npm install -g sass rollup
      - name: making build.sh executable
        run: chmod +x build.sh
      - name: execute build.sh
        run: ./build.sh
      - name: uploading built files
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out
