name: chrome

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: downloading built files
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out
      - name: making chrome.manifest.json the main manifest
        run: cp chrome.manifest.json manifest.json
      - name: downloading chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - name: installing chrome
        run: sudo apt install ./google-chrome-stable_current_amd64.deb -y
      - name: getting manifest version
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "chrome.manifest.json"
          prop_path: "version"
      - name: creating output directory
        run: mkdir great-on-deck-search.v${{steps.version.outputs.prop}}
      - name: copying files to output
        run: cp -r manifest.json out icon LICENSE great-on-deck-search.v${{steps.version.outputs.prop}}
      - name: bundling extension
        run: chrome --pack-extension=./great-on-deck-search.v${{steps.version.outputs.prop}}
      - name: uploading extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: crx
          path: great-on-deck-search.v${{steps.version.outputs.prop}}.crx
