name: chrome

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Downloading built files
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out
      - name: Making chrome.manifest.json the main manifest
        run: cp chrome.manifest.json manifest.json
      - name: Getting manifest version
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "chrome.manifest.json"
          prop_path: "version"
      - name: Creating output directory
        run: mkdir crx
      - name: Copying files to output
        run: cp -r manifest.json out icon src LICENSE crx
      - name: Installing CRX bundler
        run: npm install -g crx
      - name: Bundling extension
        run: crx pack crx -o great-on-deck-search.chrome.v${{steps.version.outputs.prop}}.crx
      - name: Uploading extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: crx
          path: great-on-deck-search.chrome.v${{steps.version.outputs.prop}}.crx

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v3
      - name: Getting manifest version
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "chrome.manifest.json"
          prop_path: "version"
      - name: Downloading crx
        uses: actions/download-artifact@v3
        with:
          name: crx
          path: ./
      - name: Creating Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "v${{steps.version.outputs.prop}}+chrome"
          files: great-on-deck-search.chrome.v${{steps.version.outputs.prop}}.crx
