name: firefox

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Downloading built files
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out
      - name: Making firefox.manifest.json the main manifest
        run: cp firefox.manifest.json manifest.json
      - name: Getting manifest version
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "firefox.manifest.json"
          prop_path: "version"
      - name: Installing zip
        run: sudo apt-get install zip -y
      - name: Bundling extension
        run: zip -r great-on-deck-search.firefox.v${{steps.version.outputs.prop}}.xpi icon out src LICENSE manifest.json
      - name: Uploading extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: xpi
          path: great-on-deck-search.chrome.v${{steps.version.outputs.prop}}.xpi
