name: firefox

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Downloading built files
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out
      - name: Making firefox.manifest.json the main manifest
        run: cp firefox.manifest.json manifest.json
      - name: Getting manifest version
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "firefox.manifest.json"
          prop_path: "version"
      - name: Installing web-ext
        run: npm install -g web-ext
      - name: Preparing files for signing
        run: mkdir xpi && cp -r icon out src LICENSE manifest.json xpi
      - name: Signing via web-ext
        run: cd xpi && web-ext sign --api-key ${{secrets.JWT_ISSUER}} --api-secret ${{secrets.JWT_SECRET}}
      - name: Renaming extension
        run: mv xpi/web-ext-artifacts/*.xpi ./great-on-deck-search.firefox.v${{steps.version.outputs.prop}}.xpi
      - name: Uploading extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: xpi
          path: great-on-deck-search.firefox.v${{steps.version.outputs.prop}}.xpi

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v3
      - name: Getting manifest version
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "firefox.manifest.json"
          prop_path: "version"
      - name: Downloading xpi
        uses: actions/download-artifact@v3
        with:
          name: xpi
          path: ./
      - name: Creating Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          automatic_release_tag: "v${{steps.version.outputs.prop}}+firefox"
          files: great-on-deck-search.firefox.v${{steps.version.outputs.prop}}.xpi

